# BIG O(N) - MOST EFFICENT ALGORITHM

# WE ARE A PASSING A NUMBER N AND WE RAN N OPERATIONS SO THATS O(N)-OPERATIONS OF N TIMES

def print_items(n):
    for i in range(n):  #LOOP THROUGH THE LIST OF N NUMBERS
        print(i) 


print_items(10)